package animasyon;


import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import json.Ayar;
import json.JsonIslemleri;

public class AnaFrame extends javax.swing.JFrame {

    public final SuruklenebilirTus benimTusum;
    private final Kronometre kronometre;
    private boolean basladiMi=false;
    private final JsonIslemleri ji= new JsonIslemleri("ayarlar.json");
    private final Ayar ayar;

    public AnaFrame() {
        
        initComponents();
        ayar=ji.jsonOku();
        benimTusum= new SuruklenebilirTus(ayar.getxKonum(), ayar.getyKonum(), ayar.getEn(), ayar.getBoy());
        benimTusum.setIcon(new ImageIcon(AnaFrame.class.getResource(ayar.getResimAdi())));
        kronometre=new Kronometre(10, benimTusum, saatLabel);
        animasyonLabel.add(benimTusum);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dugmePanel = new javax.swing.JPanel();
        oynatButton = new javax.swing.JButton();
        kaydetButton = new javax.swing.JButton();
        animasyonPanel = new javax.swing.JPanel();
        animasyonLabel = new javax.swing.JLabel();
        saatPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saatLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dugmePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        oynatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/durdur.png"))); // NOI18N
        oynatButton.setBorderPainted(false);
        oynatButton.setContentAreaFilled(false);
        oynatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oynatButtonActionPerformed(evt);
            }
        });

        kaydetButton.setBackground(new java.awt.Color(255, 255, 255));
        kaydetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/kaydet.png"))); // NOI18N
        kaydetButton.setText("Kaydet");
        kaydetButton.setBorderPainted(false);
        kaydetButton.setContentAreaFilled(false);
        kaydetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dugmePanelLayout = new javax.swing.GroupLayout(dugmePanel);
        dugmePanel.setLayout(dugmePanelLayout);
        dugmePanelLayout.setHorizontalGroup(
            dugmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dugmePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oynatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dugmePanelLayout.setVerticalGroup(
            dugmePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dugmePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oynatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dugmePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(kaydetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        animasyonPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        animasyonPanel.setPreferredSize(new java.awt.Dimension(618, 309));

        animasyonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/arkaplan.jpg"))); // NOI18N

        javax.swing.GroupLayout animasyonPanelLayout = new javax.swing.GroupLayout(animasyonPanel);
        animasyonPanel.setLayout(animasyonPanelLayout);
        animasyonPanelLayout.setHorizontalGroup(
            animasyonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(animasyonLabel)
        );
        animasyonPanelLayout.setVerticalGroup(
            animasyonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(animasyonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        saatPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Geçen Süre :");

        saatLabel.setText("00:00:00");

        javax.swing.GroupLayout saatPanelLayout = new javax.swing.GroupLayout(saatPanel);
        saatPanel.setLayout(saatPanelLayout);
        saatPanelLayout.setHorizontalGroup(
            saatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saatLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saatPanelLayout.setVerticalGroup(
            saatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saatLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(animasyonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(dugmePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dugmePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(animasyonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oynatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oynatButtonActionPerformed
        if (basladiMi) {
            kronometre.durdur();
            oynatButton.setIcon(new ImageIcon("src/resim/durdur.png"));
            basladiMi=false;
            
        }
        else{
        basladiMi=true;
         oynatButton.setIcon(new ImageIcon("src/resim/baslat.png"));
        kronometre.baslat();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_oynatButtonActionPerformed

    private void kaydetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydetButtonActionPerformed
       
        ayar.setxKonum(benimTusum.getLocation().x);
         ayar.setyKonum(benimTusum.getLocation().y);
         boolean yazildiMi=ji.jsonOlustur(ayar);
         if (yazildiMi) {
             JOptionPane.showMessageDialog(rootPane, "Ayarlar Kaydedildi","Bilgi",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_kaydetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animasyonLabel;
    private javax.swing.JPanel animasyonPanel;
    private javax.swing.JPanel dugmePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kaydetButton;
    private javax.swing.JButton oynatButton;
    private javax.swing.JLabel saatLabel;
    private javax.swing.JPanel saatPanel;
    // End of variables declaration//GEN-END:variables
}
